export interface CityData {
  slug: string;
  name: string;
  state: string;
  stateCode: string;
  industries: string;
  context: string;
  lat: number;
  lng: number;
}

export const CITY_DATA: Record<string, CityData> = {
  // Tier 1 — original 10
  ludhiana: { slug: 'ludhiana', name: 'Ludhiana', state: 'Punjab', stateCode: 'PB', industries: 'textiles, hosiery, bicycles, auto parts, pharmaceuticals', context: 'Ludhiana is India\'s largest industrial city in Punjab — a major hub for textiles, hosiery, bicycle manufacturing, and auto components. Protecting your brand in these competitive, export-driven markets is essential.', lat: 30.9010, lng: 75.8573 },
  delhi: { slug: 'delhi', name: 'Delhi', state: 'Delhi', stateCode: 'DL', industries: 'fashion, FMCG, retail, technology, food & beverage', context: 'Delhi NCR is India\'s largest consumer market and a hub for fashion, retail, and fast-moving consumer goods. With thousands of new brands launching each year, trademark registration is critical to protecting your identity.', lat: 28.6139, lng: 77.2090 },
  mumbai: { slug: 'mumbai', name: 'Mumbai', state: 'Maharashtra', stateCode: 'MH', industries: 'finance, entertainment, FMCG, real estate, media', context: 'Mumbai is India\'s commercial capital and home to the Bombay Stock Exchange, Bollywood, and thousands of registered companies. Strong trademark protection is a business necessity in this high-competition market.', lat: 19.0760, lng: 72.8777 },
  bangalore: { slug: 'bangalore', name: 'Bangalore', state: 'Karnataka', stateCode: 'KA', industries: 'IT, SaaS, startups, aerospace, biotechnology', context: 'Bangalore is India\'s Silicon Valley and the birthplace of thousands of tech startups and SaaS companies every year. Registering your brand name and logo early protects you from impersonation and domain squatting.', lat: 12.9716, lng: 77.5946 },
  hyderabad: { slug: 'hyderabad', name: 'Hyderabad', state: 'Telangana', stateCode: 'TS', industries: 'pharmaceuticals, IT, biotechnology, food processing', context: 'Hyderabad is a major centre for pharmaceutical and life-sciences companies in India. Brand protection through trademark registration is especially important in regulated industries where reputation directly impacts business.', lat: 17.3850, lng: 78.4867 },
  pune: { slug: 'pune', name: 'Pune', state: 'Maharashtra', stateCode: 'MH', industries: 'automotive, IT, education, manufacturing, defence', context: 'Pune is one of India\'s fastest-growing cities with a strong automotive and IT sector. With a large startup ecosystem and established industrial base, securing your trademark early prevents costly disputes later.', lat: 18.5204, lng: 73.8567 },
  ahmedabad: { slug: 'ahmedabad', name: 'Ahmedabad', state: 'Gujarat', stateCode: 'GJ', industries: 'textiles, chemicals, pharmaceuticals, diamond processing, FMCG', context: 'Ahmedabad is the commercial heart of Gujarat — India\'s most entrepreneur-friendly state. From textile exporters to chemical manufacturers and diamond traders, trademark protection ensures your brand is legally yours.', lat: 23.0225, lng: 72.5714 },
  chennai: { slug: 'chennai', name: 'Chennai', state: 'Tamil Nadu', stateCode: 'TN', industries: 'automobile, IT, manufacturing, healthcare, logistics', context: 'Chennai is India\'s automobile manufacturing capital and a growing IT hub. With global OEMs and tier-1 suppliers based here, protecting your brand and product names through trademark registration is essential.', lat: 13.0827, lng: 80.2707 },
  jaipur: { slug: 'jaipur', name: 'Jaipur', state: 'Rajasthan', stateCode: 'RJ', industries: 'handicrafts, gemstones, tourism, textiles, food & spices', context: 'Jaipur is renowned for its handicrafts, gemstone jewellery, blue pottery, and textile exports. Artisans and entrepreneurs in these industries are especially vulnerable to brand copying without proper trademark protection.', lat: 26.9124, lng: 75.7873 },
  chandigarh: { slug: 'chandigarh', name: 'Chandigarh', state: 'Chandigarh', stateCode: 'CH', industries: 'retail, healthcare, education, hospitality, real estate', context: 'Chandigarh is the capital of Punjab and Haryana and a rapidly growing commercial centre. As the gateway city to North India\'s economic corridor, registering your trademark here protects your brand across the entire region.', lat: 30.7333, lng: 76.7794 },

  // Tier 2 — 40 additional cities
  surat: { slug: 'surat', name: 'Surat', state: 'Gujarat', stateCode: 'GJ', industries: 'diamonds, textiles, synthetic fabrics, petrochemicals', context: 'Surat is the diamond capital of India and a global hub for synthetic textiles. With massive export volumes and highly competitive markets, brand protection through trademark registration is non-negotiable for Surat businesses.', lat: 21.1702, lng: 72.8311 },
  kolkata: { slug: 'kolkata', name: 'Kolkata', state: 'West Bengal', stateCode: 'WB', industries: 'jute, leather, IT, FMCG, steel, trading', context: 'Kolkata is Eastern India\'s commercial gateway with a rich history in jute, leather, and manufacturing. As the city transitions toward IT and services, brand protection becomes critical for both traditional and modern businesses.', lat: 22.5726, lng: 88.3639 },
  noida: { slug: 'noida', name: 'Noida', state: 'Uttar Pradesh', stateCode: 'UP', industries: 'IT, manufacturing, FMCG, media, electronics', context: 'Noida is Delhi NCR\'s tech and manufacturing hub, home to major IT parks, media companies, and electronics manufacturers. Fast-growing businesses in Noida face intense brand competition and need early trademark protection.', lat: 28.5355, lng: 77.3910 },
  gurugram: { slug: 'gurugram', name: 'Gurugram', state: 'Haryana', stateCode: 'HR', industries: 'IT, fintech, FMCG, automotive, corporate services', context: 'Gurugram (Gurgaon) is India\'s corporate capital — home to Fortune 500 company offices, IT parks, and a booming startup ecosystem. Trademark registration is a fundamental requirement for any serious business operating here.', lat: 28.4595, lng: 77.0266 },
  lucknow: { slug: 'lucknow', name: 'Lucknow', state: 'Uttar Pradesh', stateCode: 'UP', industries: 'FMCG, chikankari, government, education, healthcare', context: 'Lucknow is the capital of India\'s most populous state and a centre for chikankari textiles, food products, and a growing services sector. Brand protection is essential for artisans and FMCG businesses competing in a large market.', lat: 26.8467, lng: 80.9462 },
  kanpur: { slug: 'kanpur', name: 'Kanpur', state: 'Uttar Pradesh', stateCode: 'UP', industries: 'leather, textiles, chemicals, engineering, FMCG', context: 'Kanpur is one of India\'s largest leather and textile manufacturing centres, exporting goods globally. With a concentration of manufacturing exports, protecting your brand name and product identity is critical for long-term business success.', lat: 26.4499, lng: 80.3319 },
  nagpur: { slug: 'nagpur', name: 'Nagpur', state: 'Maharashtra', stateCode: 'MH', industries: 'oranges, mining, power, logistics, textiles', context: 'Nagpur is Central India\'s logistics and commercial hub, strategically located at the geographical centre of India. Its growing industrial base and MIHAN economic zone make brand protection a necessity for businesses expanding nationally.', lat: 21.1458, lng: 79.0882 },
  indore: { slug: 'indore', name: 'Indore', state: 'Madhya Pradesh', stateCode: 'MP', industries: 'FMCG, pharmaceuticals, textiles, IT, trading', context: 'Indore is the commercial capital of Madhya Pradesh and one of India\'s cleanest and fastest-growing cities. Its vibrant startup ecosystem and strong trading community make trademark registration a priority for any growing business.', lat: 22.7196, lng: 75.8577 },
  bhopal: { slug: 'bhopal', name: 'Bhopal', state: 'Madhya Pradesh', stateCode: 'MP', industries: 'pharmaceuticals, education, IT, tourism, government', context: 'Bhopal is the capital of Madhya Pradesh with a growing pharmaceutical sector and increasing IT presence. As the city attracts more businesses and startups, protecting brand identity early becomes essential for long-term success.', lat: 23.2599, lng: 77.4126 },
  coimbatore: { slug: 'coimbatore', name: 'Coimbatore', state: 'Tamil Nadu', stateCode: 'TN', industries: 'textiles, engineering, pumps, FMCG, agriculture', context: 'Coimbatore is Tamil Nadu\'s industrial capital and the world\'s largest pump manufacturing hub. With a strong export market in textiles and engineering goods, brand protection is essential to prevent copying in international markets.', lat: 11.0168, lng: 76.9558 },
  kochi: { slug: 'kochi', name: 'Kochi', state: 'Kerala', stateCode: 'KL', industries: 'IT, tourism, spices, seafood, shipping, startups', context: 'Kochi is Kerala\'s commercial and IT hub with a fast-growing startup ecosystem and strong export trade in spices and seafood. As businesses scale nationally and globally, trademark registration protects the brands they\'ve built.', lat: 9.9312, lng: 76.2673 },
  visakhapatnam: { slug: 'visakhapatnam', name: 'Visakhapatnam', state: 'Andhra Pradesh', stateCode: 'AP', industries: 'pharmaceuticals, steel, IT, tourism, shipbuilding', context: 'Visakhapatnam (Vizag) is Andhra Pradesh\'s largest city and a key port and industrial centre. The presence of major pharma, steel, and IT companies makes trademark registration a necessity for businesses protecting their market position.', lat: 17.6868, lng: 83.2185 },
  patna: { slug: 'patna', name: 'Patna', state: 'Bihar', stateCode: 'BR', industries: 'agriculture, education, FMCG, government, trading', context: 'Patna is Bihar\'s capital and a major commercial centre serving one of India\'s largest states. With a booming FMCG and education sector, brand protection is increasingly important as businesses from Patna compete nationally.', lat: 25.5941, lng: 85.1376 },
  vadodara: { slug: 'vadodara', name: 'Vadodara', state: 'Gujarat', stateCode: 'GJ', industries: 'chemicals, petrochemicals, engineering, textiles, pharmaceuticals', context: 'Vadodara is Gujarat\'s chemical and engineering capital, home to ONGC, GSFC, and hundreds of chemical manufacturers. In export-heavy, IP-sensitive industries like chemicals and pharma, trademark registration is a critical business asset.', lat: 22.3072, lng: 73.1812 },
  rajkot: { slug: 'rajkot', name: 'Rajkot', state: 'Gujarat', stateCode: 'GJ', industries: 'engineering, jewellery, textiles, auto parts, FMCG', context: 'Rajkot is Saurashtra\'s industrial and commercial centre, known for precision engineering, jewellery, and auto components. With major export markets in the Middle East and Africa, brand protection is essential for Rajkot businesses going global.', lat: 22.3039, lng: 70.8022 },
  agra: { slug: 'agra', name: 'Agra', state: 'Uttar Pradesh', stateCode: 'UP', industries: 'leather, footwear, tourism, handicrafts, FMCG', context: 'Agra is globally known for the Taj Mahal but is equally important as India\'s leather and footwear capital. With major export operations in leather goods, artisans and manufacturers need trademark protection to prevent brand copying.', lat: 27.1767, lng: 78.0081 },
  amritsar: { slug: 'amritsar', name: 'Amritsar', state: 'Punjab', stateCode: 'PB', industries: 'textiles, tourism, food processing, carpets, pharmaceuticals', context: 'Amritsar is Punjab\'s religious and cultural capital and a major commercial hub near the Pakistan border. Its textile, food processing, and tourism businesses need trademark registration to protect brands in these competitive sectors.', lat: 31.6340, lng: 74.8723 },
  jalandhar: { slug: 'jalandhar', name: 'Jalandhar', state: 'Punjab', stateCode: 'PB', industries: 'sports goods, textiles, leather, furniture, hardware', context: 'Jalandhar is the world\'s sports goods capital, producing over 80% of India\'s sports equipment exports. With significant international buyers and competing manufacturers, brand protection through trademark registration is essential for any Jalandhar business.', lat: 31.3260, lng: 75.5762 },
  jodhpur: { slug: 'jodhpur', name: 'Jodhpur', state: 'Rajasthan', stateCode: 'RJ', industries: 'handicrafts, textiles, tourism, agro-processing, furniture', context: 'Jodhpur is the Blue City of Rajasthan and a major centre for handicrafts, antique furniture, and textile exports. With international buyers from Europe and the USA, Jodhpur businesses need trademark protection to prevent brand copying.', lat: 26.2389, lng: 73.0243 },
  varanasi: { slug: 'varanasi', name: 'Varanasi', state: 'Uttar Pradesh', stateCode: 'UP', industries: 'silk, handicrafts, tourism, FMCG, education', context: 'Varanasi is the silk weaving capital of India and one of the world\'s oldest living cities. Banarasi silk and handicrafts face significant copying problems — trademark registration is essential for weavers and artisans protecting their identity.', lat: 25.3176, lng: 82.9739 },
  dehradun: { slug: 'dehradun', name: 'Dehradun', state: 'Uttarakhand', stateCode: 'UK', industries: 'education, IT, tourism, FMCG, pharmaceuticals', context: 'Dehradun is Uttarakhand\'s capital and a rapidly growing city with a strong education sector and emerging IT and pharmaceutical industries. As businesses grow from local to national, trademark registration becomes a key priority.', lat: 30.3165, lng: 78.0322 },
  mysore: { slug: 'mysore', name: 'Mysore', state: 'Karnataka', stateCode: 'KA', industries: 'silk, sandalwood, tourism, IT, FMCG', context: 'Mysore is famous for its silk, sandalwood products, and tourism industry. With globally recognised products at risk of counterfeiting, trademark registration is critical for Mysore businesses protecting their GI-associated brands.', lat: 12.2958, lng: 76.6394 },
  thiruvananthapuram: { slug: 'thiruvananthapuram', name: 'Thiruvananthapuram', state: 'Kerala', stateCode: 'KL', industries: 'IT, tourism, healthcare, education, handicrafts', context: 'Thiruvananthapuram is Kerala\'s capital and a growing IT and healthcare hub. With Technopark as one of India\'s largest IT parks, tech startups and service businesses increasingly need trademark protection as they scale.', lat: 8.5241, lng: 76.9366 },
  mangalore: { slug: 'mangalore', name: 'Mangalore', state: 'Karnataka', stateCode: 'KA', industries: 'chemicals, seafood, cashew, banking, education', context: 'Mangalore is a major port city and commercial hub in coastal Karnataka. With significant chemical exports, seafood processing, and cashew industries, brand protection is essential for Mangalore businesses competing in international markets.', lat: 12.9141, lng: 74.8560 },
  nashik: { slug: 'nashik', name: 'Nashik', state: 'Maharashtra', stateCode: 'MH', industries: 'wine, grapes, pharmaceuticals, engineering, FMCG', context: 'Nashik is India\'s wine capital and a major pharmaceutical and engineering hub. With premium food and beverage brands at constant risk of copying, trademark registration is a necessity for Nashik\'s growing branded goods sector.', lat: 19.9975, lng: 73.7898 },
  aurangabad: { slug: 'aurangabad', name: 'Aurangabad', state: 'Maharashtra', stateCode: 'MH', industries: 'automobiles, pharmaceuticals, textiles, tourism', context: 'Aurangabad is Maharashtra\'s fastest-growing industrial city and home to major automobile manufacturers like Bajaj and Skoda. With significant manufacturing and pharma exports, protecting brand names and product marks is essential.', lat: 19.8762, lng: 75.3433 },
  bhubaneswar: { slug: 'bhubaneswar', name: 'Bhubaneswar', state: 'Odisha', stateCode: 'OD', industries: 'IT, steel, mining, tourism, handicrafts', context: 'Bhubaneswar is Odisha\'s capital and a rapidly growing IT and government hub. As the city\'s startup ecosystem matures and traditional businesses professionalise, trademark registration protects the brands businesses spend years building.', lat: 20.2961, lng: 85.8245 },
  raipur: { slug: 'raipur', name: 'Raipur', state: 'Chhattisgarh', stateCode: 'CG', industries: 'steel, mining, agriculture, FMCG, trading', context: 'Raipur is Chhattisgarh\'s capital and India\'s steel trading hub. With a concentration of steel producers, mineral traders, and agro-processors, brand protection ensures businesses maintain their competitive advantage in this resource-rich market.', lat: 21.2514, lng: 81.6296 },
  guwahati: { slug: 'guwahati', name: 'Guwahati', state: 'Assam', stateCode: 'AS', industries: 'tea, oil, FMCG, tourism, handicrafts', context: 'Guwahati is Northeast India\'s commercial gateway and a hub for tea, oil, and FMCG distribution. As the primary business city of the Northeast, trademark registration protects businesses from the growing problem of brand copying in this expanding market.', lat: 26.1445, lng: 91.7362 },
  vijayawada: { slug: 'vijayawada', name: 'Vijayawada', state: 'Andhra Pradesh', stateCode: 'AP', industries: 'agriculture, FMCG, textiles, construction, education', context: 'Vijayawada is Andhra Pradesh\'s commercial capital and a major agriculture trade hub. With a fast-growing FMCG sector and expanding retail brands, trademark registration is increasingly important for businesses scaling from regional to national.', lat: 16.5062, lng: 80.6480 },
  meerut: { slug: 'meerut', name: 'Meerut', state: 'Uttar Pradesh', stateCode: 'UP', industries: 'sports goods, scissors, sugarcane, education, FMCG', context: 'Meerut is globally known for sports goods, scissors, and musical instruments. With significant export activity and well-known product categories, businesses in Meerut need trademark protection to defend their brand identity in competitive markets.', lat: 28.9845, lng: 77.7064 },
  prayagraj: { slug: 'prayagraj', name: 'Prayagraj', state: 'Uttar Pradesh', stateCode: 'UP', industries: 'education, government, FMCG, tourism, services', context: 'Prayagraj (Allahabad) is a major education and government hub in Uttar Pradesh. With a growing services sector and FMCG market, trademark registration helps local businesses protect their brands as they compete with national players.', lat: 25.4358, lng: 81.8463 },
  ghaziabad: { slug: 'ghaziabad', name: 'Ghaziabad', state: 'Uttar Pradesh', stateCode: 'UP', industries: 'manufacturing, IT, FMCG, auto parts, chemicals', context: 'Ghaziabad is NCR\'s manufacturing hub, producing everything from electronic goods to auto parts and chemicals. As part of the Delhi-NCR market, businesses in Ghaziabad face intense competition and need trademark protection to secure their brand identity.', lat: 28.6692, lng: 77.4538 },
  kota: { slug: 'kota', name: 'Kota', state: 'Rajasthan', stateCode: 'RJ', industries: 'education, coaching, chemicals, textiles, FMCG', context: 'Kota is India\'s coaching capital and a major petrochemical hub. Education businesses, coaching institutes, and chemical manufacturers in Kota increasingly need trademark registration to protect their brand from imitation and passing-off.', lat: 25.2138, lng: 75.8648 },
  goa: { slug: 'goa', name: 'Goa', state: 'Goa', stateCode: 'GA', industries: 'tourism, mining, food & beverage, real estate, handicrafts', context: 'Goa is India\'s premier tourism destination and a growing hub for premium food, beverage, and lifestyle brands. With international tourist footfall and high brand visibility, trademark registration protects Goa businesses from copying by imitators.', lat: 15.2993, lng: 74.1240 },
  hubballi: { slug: 'hubballi', name: 'Hubballi', state: 'Karnataka', stateCode: 'KA', industries: 'agriculture, cotton, FMCG, engineering, trading', context: 'Hubballi-Dharwad is North Karnataka\'s commercial capital and a major cotton and agricultural trade hub. Growing retail and FMCG businesses in this region need trademark registration to protect their brands as they expand beyond local markets.', lat: 15.3647, lng: 75.1240 },
  trichy: { slug: 'trichy', name: 'Trichy', state: 'Tamil Nadu', stateCode: 'TN', industries: 'textiles, engineering, education, FMCG, agriculture', context: 'Tiruchirapalli (Trichy) is Tamil Nadu\'s central commercial hub with a strong engineering and textile base. With significant manufacturing exports and a growing education sector, trademark registration is essential for businesses building recognisable brands.', lat: 10.7905, lng: 78.7047 },
  madurai: { slug: 'madurai', name: 'Madurai', state: 'Tamil Nadu', stateCode: 'TN', industries: 'textiles, jasmine, tourism, FMCG, engineering', context: 'Madurai is Tamil Nadu\'s cultural capital and a major textile and FMCG hub. Known for Madurai jasmine and handloom textiles, businesses in this city need trademark registration to protect their geographical indication-linked products from imitation.', lat: 9.9252, lng: 78.1198 },
  'navi-mumbai': { slug: 'navi-mumbai', name: 'Navi Mumbai', state: 'Maharashtra', stateCode: 'MH', industries: 'IT, chemicals, pharmaceuticals, logistics, retail', context: 'Navi Mumbai is a planned satellite city that has become a major IT and chemical hub. With JNPT port nearby and major corporate offices, businesses in Navi Mumbai need trademark protection to compete in both domestic and export markets.', lat: 19.0330, lng: 73.0297 },
  thane: { slug: 'thane', name: 'Thane', state: 'Maharashtra', stateCode: 'MH', industries: 'manufacturing, chemicals, IT, FMCG, real estate', context: 'Thane is Mumbai\'s industrial neighbour and one of Maharashtra\'s fastest-growing cities. With a dense concentration of chemical plants, IT companies, and FMCG distributors, trademark registration is a key business requirement for Thane enterprises.', lat: 19.2183, lng: 72.9781 },
};

export function getCityData(slug: string): CityData | null {
  return CITY_DATA[slug.toLowerCase()] ?? null;
}

export const ALL_CITY_SLUGS = Object.keys(CITY_DATA);
